# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\NodeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Node_Form(object):
    def setupUi(self, Node_Form):
        Node_Form.setObjectName("Node_Form")
        Node_Form.resize(1163, 800)
        Node_Form.setMinimumSize(QtCore.QSize(700, 400))
        Node_Form.setMaximumSize(QtCore.QSize(1600, 800))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Node_Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(Node_Form)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.activ_docx_treeWidget = QtWidgets.QTreeWidget(self.widget_4)
        self.activ_docx_treeWidget.setObjectName("activ_docx_treeWidget")
        self.activ_docx_treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_3.addWidget(self.activ_docx_treeWidget)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.nodes_treeWidget = QtWidgets.QTreeWidget(self.widget_3)
        self.nodes_treeWidget.setObjectName("nodes_treeWidget")
        self.nodes_treeWidget.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.nodes_treeWidget)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.operation_widget = QtWidgets.QWidget(Node_Form)
        self.operation_widget.setMaximumSize(QtCore.QSize(1600, 160))
        self.operation_widget.setObjectName("operation_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.operation_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2.addWidget(self.operation_widget)

        self.retranslateUi(Node_Form)
        QtCore.QMetaObject.connectSlotsByName(Node_Form)

    def retranslateUi(self, Node_Form):
        _translate = QtCore.QCoreApplication.translate
        Node_Form.setWindowTitle(_translate("Node_Form", "Form"))
        self.label_2.setText(_translate("Node_Form", "Активные документы в блокчейне"))
        self.label.setText(_translate("Node_Form", "Все узлы блокчейна"))
